apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.hypervisor.lukeaddison.co.uk
spec:
  insecureSkipTLSVerify: true
  group: hypervisor.lukeaddison.co.uk
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: api
    namespace: hypervisor
  version: v1alpha1
