apiVersion: v1
kind: Namespace
metadata:
  name: kube-qemu
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-qemu
  namespace: kube-qemu
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-qemu-apiserver
  namespace: kube-qemu
  labels:
    app: kube-qemu
    role: apiserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kube-qemu
      role: apiserver
  template:
    metadata:
      labels:
        app: kube-qemu
        role: apiserver
    spec:
      serviceAccountName: kube-qemu
      containers:
      - name: kube-qemu
        image: dippynark/kube-qemu-apiserver:canary
        imagePullPolicy: Always
        args:
        - "kube-qemu-apiserver"
        - "--etcd-servers=http://localhost:2379"
        - --v=100
      - name: etcd
        image: quay.io/coreos/etcd:v3.0.17
---
apiVersion: v1
kind: Service
metadata:
  name: kube-qemu-apiserver
  namespace: kube-qemu
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: kube-qemu
    role: apiserver
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.hypervisor.k8s.co
spec:
  insecureSkipTLSVerify: true
  group: hypervisor.k8s.co
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: kube-qemu-apiserver
    namespace: kube-qemu
  version: v1alpha1
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: kube-qemu-auth-reader
  namespace: kube-qemu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: kube-qemu
  namespace: kube-qemu